### PR TITLE
Added Dockerfile to project

### PR DESCRIPTION
**Pull request by andmos**
👋 Hi guys! 

I needed a `Dockerfile` as a part of my CI pipeline, so decided to contribute it upstream. Example run:
```
docker run -v $(pwd):/mnt -it andmos/alex README.md
# README.md: no issues found
```

### CODE REVIEW

**Comment by Murderlon** [comment]
Hi @andmos, cool stuff! But I feel like this is something you make specifically for yourself when you need it and it doesn't need to be in this repo.

Have some good arguments? Otherwise I think I'll close this.

**Comment by andmos** [comment]
I see your point. The best argument I guess is that the `Dockerfile` provides a (now) standardized way of running / including apps in local development flow / CI /deployment without having Node or NPM installed. It makes the project more accessible to non-JS developers who might not have Node installed, or make a QA pipeline for blogs or other writing decoupled from the runtime itself. For my writing I check links with [awesome_bot](https://github.com/dkhamsing/awesome_bot) and the markdown-style with [MarkdownLint](https://github.com/igorshubovych/markdownlint-cli) without having built the projects or installed Ruby / Node. Might just be me of course, but it is a nice feature to have available 😃

**Comment by Murderlon** [comment]
@wooorm what do you think? Nice to have with some documentation in the README?

**Comment by wooorm** [comment]
I think I’d prefer docs over a dockerfile. @andmos Do you think that makes sense as well?
This is a Node project, and installing it through npm/yarn is the preferred way. I also don’t use Docker so I can’t maintain, test, or update it when needed. Finally, as you created the file yourself already, I feel that Docker users already have the know-how to add a Node project when needed, even if that project doesn’t provide a Dockerfile!

**Comment by andmos** [comment]
It's totally cool guys. Since the Dockerfile don't _build_ the app, only wrap npm install, I can create a repository only containing the Dockerfile hand have a automated build to the dockerhub from that. 
Cheers!

**Pull request closed without merging**
