### PR TITLE
Readme insensitivity.

### PR DESCRIPTION
**Pull request by sundown**
Replace "unis*x" in readme. Potentially PTSD inducing.

### CODE REVIEW

**Comment by wooorm** [comment]
Can you explain? E.g., with a source?

**Comment by wooorm** [comment]
The way you throw PTSD around indicates to me you’re not serious, so I’ll close this. Please do provide a source if you’re honest.

**Comment by sundown** [comment]
The term is very exclusionary toward the trans community. I think it's very obvious that such a term eludes to the binary, and debunked concept of two genders. I thought Alex was about mitigating this type of harmful language. https://www.dailymail.co.uk/news/article-5453007/Council-change-unisex-toilet-signs-offensive.html

**Comment by wooorm** [comment]
This project gains lots of attention from trolls. I read your tone as rather aggressive, e.g., classifying things as “obvious” whereas language often isn‘t, or dropping PTSD when uncalled for. The dailymail is not a good source. From these points, I don’t trust you and am locking this. The point about `unisex` may be good but you’re making a bad argument for it. Please try again if you have good faith and want to make things better.

**Pull request closed without merging**
