### PR TITLE
Minor grammatical changes to the docs.

### PR DESCRIPTION
**Pull request by edorado93**

### CODE REVIEW

**Comment by wooorm** [comment]
Hey @edorado93, could you expand on why these changes are needed?

**Comment by edorado93** [comment]
Hey @wooorm, these changes don't fix any pressing issues as such. However, they fix-up the documentation a bit. e.g. 

```
A window will **not** pop up.
```
This was written twice in the documentation in two consective lines and I think that was by mistake. Again, nothing major but just some README fixes.

**Comment by edorado93** [comment]
@wooorm Sure thing. I'll add the line back. But as @Murderlon said, the line is there to convey that linting is disabled until `<!--alex enable dad-mom-->`. I still feel it's a bit confusing at first. Can we project it in some other way maybe? If you feel its ok, I'll add the line back and you can go ahead with the merge. 

Maybe we can have something like

```
<!--alex disable dad-mom-->

SENTENCE 1
A window will **not** pop up.

SENTENCE 2
A window will **not** pop up.

<!--alex enable dad-mom-->

SENTENCE 3
A window will pop up.
```

Something along these lines. What do you think?

**Comment by wooorm** [comment]
@edorado93 Thanks for clarifying! Maybe we can reword that line, in all places it occurs, in a better way?

For example, something along these lines:

```
A message for this sentence will pop up.

...

Another message for this sentence will pop up.

...

No message for this sentence will pop up.

...

```

**Comment by edorado93** [comment]
@wooorm Yes. That would be better. I'll scan the documentation and make these changes wherever applicable.

**Comment by wooorm** [comment]
@edorado93 Still working on this? Anything we can do to help?

**Comment by edorado93** [comment]
@wooorm Yes. I am working on this. Not getting time to look into it due to some other work. I will post here if I need some help. 👍

**Comment by edorado93** [comment]
@wooorm I made the changes to the README. I did a rebase to just have a single commit. Let me know if you want me to change something else.

**Comment by Murderlon** [comment]
@edorado93 perfect, all good to go :)

**Comment by edorado93** [comment]
Thanks a ton @Murderlon 😄

**Pull request merged**
