### PR TITLE
Add favicons to website

### LINKED ISSUE #225: Add website favicon
### Subject of the issue

Add a favicon to the website.

### Your environment
MacOS 10.14
Node v8.11.3 and npm v6.4.1, Chrome v69.0.3497.100

### Steps to reproduce
Add a favicon.png to the HTML head. 

### Expected behaviour
Favicon is displayed on desktop and mobile browsers (e.g. when saved as mobile bookmark). 

### Actual behaviour
No favicon has been added yet. 

I can add this and push this quickly if you're into this idea and this design - here is what I'm thinking of adding (even as a placeholder if you'd like a different design eventually): 

favicon

### PR DESCRIPTION
**Pull request by laurenmayers**
Closes #225. 
Used realfavicongenerator.net to create 260x260px cross-browser desktop & mobile favicons for Alex website.

### CODE REVIEW

**Comment by laurenmayers** [comment]
@Murderlon Ah, I knew something was going wrong. I'm having a little trouble sorting out the merge conflict, not sure what sort of monster I've created here 😅
If I run `git pull` or `git reset HEAD~5` I get: 

```
nothing added to commit but untracked files present (use "git add" to track)
Updating b644e4f..4ddc5ad
error: The following untracked working tree files would be overwritten by merge:
        favicon_package_v0.16/android-chrome-192x192.png
        favicon_package_v0.16/android-chrome-256x256.png
        favicon_package_v0.16/apple-touch-icon.png
        favicon_package_v0.16/browserconfig.xml
        favicon_package_v0.16/favicon-16x16.png
        favicon_package_v0.16/favicon-32x32.png
        favicon_package_v0.16/favicon.ico
        favicon_package_v0.16/mstile-150x150.png
        favicon_package_v0.16/safari-pinned-tab.svg
        favicon_package_v0.16/site.webmanifest
        src/hacktoberfest.png
Please move or remove them before you merge.
Aborting
```
I tried the `git reset HEAD~5` a few times and just noticed each time it's pushing my branch further and further behind origin/website, and I'm not sure how to catch up. I'd really appreciate any advice on how I can redeem myself here, I've somehow gone down a rabbit hole :(

**Comment by Murderlon** [comment]
@laurenmayers I'd probably delete the untracked files for now and then do `git checkout .`, which will clear as much as possible back to begin. You can then probably do a `git pull` and maybe try a few things from there. If you're stuck again, please return with the full output of `git status` :)

**Comment by laurenmayers** [comment]
@Murderlon Thanks for your help. I've managed to get everything back to where it was locally (pre favicons) using your advice, and then tried to revert the related commits using `git revert <SHA> ` as per [these](https://blog.github.com/2015-06-08-how-to-undo-almost-anything-with-git/#undo-a-public-change) - but they are still visible in [my fork] (https://github.com/laurenmayers/alex/tree/website) 🤔
So now that my local environment is back to square one (pre-favicons), how can I get my fork back to square one too? I can still see the two files I reverted: 
```
favicon_package_v0.16
src/index.html
```
Git status at time of writing:
```
MacBook-Pro:alex laurenmayers$ git status
On branch website
Your branch is ahead of 'origin/website' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
MacBook-Pro:alex laurenmayers$
```

**Comment by wooorm** [comment]
If you have the proper thing locally, but something else on your remote branch (in this PR), you can *force push* (`git push --force`) your changes to the remote.
Normally you want to be careful overwriting remote things, but as this is your branch, it’s fine! 👍

**Comment by laurenmayers** [comment]
@wooorm @Murderlon  Hey! I was hoping I could finish this off after this weekend, if you don't mind the delay? Life just got a bit hectic but I want to finish this as soon as I can! :)

**Comment by Murderlon** [comment]
That's totally fine. You already took the initiative of coming up with this and working on it in your free time so don't feel pressured to finish things as quickly as possible.

**Pull request closed without merging**
