### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by BNewing**
This PR reshuffles the heading levels so that there's only one `<h1>` on the page. This makes it more usable for screen reader users. This closes issue #257.

I've left 'Made with love' as a heading level after some thought. I was originally going to make it not a title, but I think it is a title - it is talking about the creators behind the project, and is about how it was made. Very open to other thoughts or input on that!

### CODE REVIEW

**Comment by BNewing** [comment]
Most recent commit fixes #259 

I choose a new purple that is super close to the existing purple, to the point where it's hard to tell them appart. But if you don't like it I totally understand! 

(Sorry if I'm making a mess of this! Is this the right way of contributing to the `website` branch?)

**Comment by wooorm** [comment]
Hey Beverly, you are doing great! 👍

**Comment by BNewing** [comment]
Thank you @wooorm! Should I be creating a branch of of of `website` and requesting to merge into that, to separate things out into separate PRs? At the moment, I'm rolling things into the one PR, which means it'd be harder to pick and choose things you do want to go in, and I'm super conscious of that you might not want to accept the brand colour one!

**Comment by wooorm** [comment]
Hi again! I think it’s good to make the colour darker. There wasn’t a lot of thinking behind it (it’s mathematically right between red and blue).

I have recently used the [primer colors](https://github.com/primer/primitives/blob/4ea9fe27590798071b138cb831068f6a9b9eac9b/modules/primer-colors/colors.json#L10) for a couple of websites, and I think those give good results. It would give `#6f42c1` for purple (which is a bit darker than the current, `#8060e5`; and your proposal, `#7c5be5`)

One thing to do though is that we’d need to update the colour in more places:

- The GH corner has a different purple, weird!
- Logos and other assets.

For this to land, we at least need to update the assets. But also, I find the current logo a bit boring, so while we are at it, why not something else? 🤔🤔 What do you think?

**Comment by BNewing** [comment]
Ok! I'm happy to go with whatever colour you like :D I just poked around on this [colour contrast tool](https://contrast-checker.glitch.me/) until I had something that passed! 

Hmmmm. I am awful at design, and logos! I did quite like the simplicity of the logo at it currently is. The A in the favicon is a little hard to read though. On that note - what software do you use to generate/alter images like that? Do you have any particular recommendations? The last time I made a favicon I used an online tool that wasn't great, and I've not done much with assets since. Keen to have a go though!

I'll do a PR to make the GitHub icon colour consistent with the one in the PR - that'll make it easier to do a search and replace on it later if we change it to another one :)

**Comment by wooorm** [comment]
OK let’s move the icon conversation to a new issue, I have a friend that’s able to generate new (fav)icons!

That lets us finish this PR, could you update the changes to colours here to use `#6f42c1`? Then we can merge it!

**Comment by wooorm** [comment]
New media assets went really fast (GH-261, GH-262, GH-263), so no need to update the colours anymore, this is good to go!

**Comment by BNewing** [comment]
Thank you for merging this in :D

**Pull request merged**
