### PR TITLE
add href jump to website landing page

### LINKED ISSUE #223: Add functionality to down arrow on landing page
### Subject of the issue

Add functionality to white down arrow on landing page view so that the page scrolls down to content when clicked:

screen shot 2018-10-08 at 10 44 33 am

### Your environment

*   MacOS 10.14
*   Node v8.11.3 and npm v6.4.1, Chrome v69.0.3497.100

### Steps to reproduce

I will create a click event on the down arrow element so that the page scrolls to content.section

### Expected behaviour

The page scrolls to content when down arrow is clicked.

### Actual behaviour

Nothing happens when down arrow is clicked.

I would like to be assigned to this issue and start working on it if I can.

### PR DESCRIPTION
**Pull request by laurenmayers**
Closes #223. 

When clicked, the white down arrow on the website landing page now jumps to the #content section. 

I would like to add smooth scrolling, however I was having trouble seeing my changes to the index.js file when I was working on this - even testing console.logs did not show up for me. I would really appreciate any pointers as I'd love to add that feature.

### CODE REVIEW

**Comment by brendo** [comment]
> I would like to add smooth scrolling, however I was having trouble seeing my changes to the index.js file when I was working on this - even testing console.logs did not show up for me. I would really appreciate any pointers as I'd love to add that feature.

I only learnt recently that smooth scrolling can be achieved in some browsers just with CSS! Give [`scroll-behaviour`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) a go and you might not need to add any JS at all 💃

**Comment by laurenmayers** [comment]
Hey @brendo, I just learnt about `scroll-behaviour` myself, I'll give it a go! 
@Murderlon That explains things! Thanks for that, I'll work on this now :)

**Comment by laurenmayers** [comment]
All done! Love the smooth-scrolling property 👌🏻
I realized after pushing the updated code that I left an empty line on line 4 which interfered with the  changes review on GitHub, hence the latest commit.

**Comment by laurenmayers** [comment]
@Murderlon Ooh yes! I didn't consider that, my apologies. It's second nature to use my formatter now, and yes, it's Prettier. I'll be more mindful of that from now on!

**Pull request merged**
